Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs
Detects cyclic loops and adds a $ref referencing the $id of the already generated dictionary/value (like JSON.NET handles references).
=> Detect cyclic loops and add $ref and $id properties

README.md
Pretty trivial, just fixes up the link to Serilog.net by adding a newline in the markdown.
=> Fix readme link - just needs a new line

Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs
Existing mechanism for breaking circular references did not take into account that 
dictionaries and enumerables can also be part of circular object graph. This change
treats enumerables and dictionaries similarly to regular objects: once they are 
destructured, they are remembered.
For enumerables the solution is limited. Because they lack properties (enumerables
are serialized directly as lists) there is no way of adding "$id" property. I decided
to keep it simple and just leave "circular ref" marker, without getting into details.
Additionally, fix was made for "reference" id's generation which was inconsistent 
and could lead to "hanging" $refs.
I added straithforward tests with scenarios that failed with previous implementation.
=> Fix reflection based destructuring of cyclic enumerables and dictionaries

Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs
Destructurer failed in case of exception with property with name "Type".
By failure, I mean throwing "Key already present in dictionary" exception and
not logging exception data at all.
This change introduces fallback to "$Type" property and silent skip of 
appending exception type if "$Type" is taken as well.
=> Fix adding exception type description if "Type" property is present

Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs
'is' is more readable, casts in place and is more performant
=> Use 'is' pattern matching instead of IsAssignableFrom

CHANGELOG.md, Serilog.Exceptions.sln, Source/Serilog.Exceptions/Destructurers/OperationCanceledExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs, Tests/Serilog.Exceptions.Benchmark/Serilog.Exceptions.Benchmark.csproj, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, Tests/Serilog.Exceptions.Test/Destructurers/OperationCanceledExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/TaskCanceledExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
Continuation of #65, closes #64 
I will first cleanup style-cop warnings and tests, then add new tests and complete PR.
Work in progress.
=> Add support for OperationCancelledException and TaskCancelledException

.github/CONTRIBUTING.md, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionEnricher.cs, Source/Serilog.Exceptions/Core/IDestructuringOptions.cs, Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs
Implements https://github.com/RehanSaeed/Serilog.Exceptions/issues/156
=> Add WithoutReflectionBasedDestructurer option

Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs, Directory.Build.props, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs
=> Bump Microsoft.CodeAnalysis.FxCopAnalyzers from 3.0.0 to 3.3.0

Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Destructurers/SocketExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, Tests/Serilog.Exceptions.Test/Destructurers/SocketExceptionDestructurerTest.cs
Resolves #249
I decided to keep things simple by only adding properties for `SocketErrorCode` and its documentation.
The properties and inheritance hierarchy varies for `SocketException` depending on the target runtime.  For example, it has properties [`ErrorCode`](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketexception.errorcode?view=netcore-3.1#System_Net_Sockets_SocketException_ErrorCode) and [`NativeErrorCode`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.win32exception.nativeerrorcode?view=netcore-3.1#System_ComponentModel_Win32Exception_NativeErrorCode) and the inheritance hierarchy is
> Exception -> SystemException -> ExternalException -> Win32Exception -> SocketException
when [targeting .NET Core …
=> Added SocketExceptionDestructurer #249

.editorconfig, Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs, Benchmarks/Serilog.Exceptions.Benchmark/Serilog.Exceptions.Benchmark.csproj, Directory.Build.props, Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Source/Serilog.Exceptions.MsSqlServer/Serilog.Exceptions.MsSqlServer.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionEnricher.cs, Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionTypeLoadExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs, Source/Serilog.Exceptions/Serilog.Exceptions.csproj, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj, Tools/ExceptionFinderTool/ExceptionFinderTool.csproj, build.cake, dotnet-tools.json, global.json
- Upgrade to .NET Core SDK 5.0.100.
- Use latestMajor .NET SDK.
- Bump Cake.Tool from 0.38.5 to 1.0.0.
- Update the `.editorconfig` file which has changed in a breaking way (https://github.com/RehanSaeed/EditorConfig/pull/42) to support VS 16.8.
- Enable `EnforceCodeStyleInBuild` (This is awesome).
- Fix all the new warnings.
- Switch from `is object` to `is not null`. This has been on my mind for a long time. There is a lot more that could be done but getting some C# 9 in early.
=> Upgrade to .NET Core SDK 5.0.100

Benchmarks/Serilog.Exceptions.Benchmark/Point.cs, Tests/.editorconfig, appveyor.yml, dotnet-tools.json, global.json
- Bump .NET SDK from 5.0.100 to 5.0.102.
- Bump cake.tool to RC2.
- Fix warnings.
- Fix AppVeyor Mac OS .NET SDK install path.
=> Up Bump .NET SDK from 5.0.100 to 5.0.102

Directory.Build.props, dotnet-tools.json
- Bump StyleCop.Analyzers from 1.1.118 to 1.2.0-beta.321, this allows use of new C# features without warnings.
- Bump dotnet-cake from 1.0.0-rc0002 to 1.0.0-rc0003.
=> Bump StyleCop.Analyzers from 1.1.118 to 1.2.0-beta.321

.editorconfig, Benchmarks/Serilog.Exceptions.Benchmark/DestructuringBenchmark.cs, Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions.EntityFrameworkCore/Destructurers/DbUpdateExceptionDestructurer.cs, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/TaskCanceledExceptionDestructurerTest.cs
=> Bump .editorconfig to 2.1.0

Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs, Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs
I may prepare another fix to tackle the problem of gathering properties from a type taking into account possible redefinitions.
However, I consider the change proposed here good practice for library robustness.
Fixes #343
=> Fix reflection based destructuring for redefined property

README.md
Just noticed that json config example is missing, which may be useful for someone for fast start up.
Also closes #323.
=> Configuration example

.github/workflows/build.yml, Benchmarks/Serilog.Exceptions.Benchmark/DestructuringBenchmark.cs, Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs, Benchmarks/Serilog.Exceptions.Benchmark/Serilog.Exceptions.Benchmark.csproj, Directory.Build.props, README.md, Source/Directory.Build.props, Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Source/Serilog.Exceptions.MsSqlServer/Serilog.Exceptions.MsSqlServer.csproj, Source/Serilog.Exceptions.Refit/Destructurers/ApiExceptionDestructurer.cs, Source/Serilog.Exceptions.Refit/Serilog.Exceptions.Refit.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionEnricher.cs, Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs, Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs, Source/Serilog.Exceptions/Reflection/ReflectionPropertyInfo.cs, Source/Serilog.Exceptions/Serilog.Exceptions.csproj, Tests/Serilog.Exceptions.Test/Destructurers/DbUpdateExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj, Tools/ExceptionFinderTool/ExceptionFinderTool.csproj, Tools/ExceptionFinderTool/Program.cs, azure-pipelines.yml, global.json
- Add .NET 6 target framework.
- Destructure many more exceptions without reflection.
- Remove .NET Standard 1.6 target framework.
- Remove support for Mono.
- Add more target frameworks to EF, Refit etc. packages based on those NuGet packages.
- Fix wrong `paramName` set in `ArgumentNullException`.
- Use `ArgumentNullException.ThrowIfNull` where available.
- Add embedded `README.md` to NuGet packages (https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile).
Will not merge until .NET 6 is released. Remaining work:
- Upgrade to EF Core 6.
- Check the target frameworks that Serilog will support in .NET 6.
- Will update the `.editorconfig` in a later PR and go with file scoped namespaces.
=> Add .NET 6 and C# 10 Support

Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Destructurers/RegexMatchTimeoutExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/RegexMatchTimeoutExceptionDestructurerTests.cs
As per https://github.com/RehanSaeed/Serilog.Exceptions/issues/418, adding a custom destructurer for RegexMatchTimeoutException.
After the fail that was PR #456 have now made sure that the commit is applied to main instead of master...
=> Add RegexMatchTimeoutExceptionDestructurer for RegexMatchTimeoutException

README.md, Serilog.Exceptions.sln, Source/Serilog.Exceptions.Grpc/Destructurers/RpcExceptionDestructurer.cs, Source/Serilog.Exceptions.Grpc/Properties/AssemblyInfo.cs, Source/Serilog.Exceptions.Grpc/Serilog.Exceptions.Grpc.csproj, Tests/Serilog.Exceptions.Test/Destructurers/RpcExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
Implemented a gRPC destructurer ([RpcException](https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Core.Api/RpcException.cs)). 
Added some tests.
=> Implement gRPC destructurer

README.md
Hello! Thank you for creating this project. I've just stumbled upon this and was reading `README` when noticed warning for EF Core users. Warning looks quite important, but link to it seems to be invalid.
This PR fixes anchor link to warning for EF Core users. Change was tested in `Google Chrome Version 114.0.5735.106 (Official Build) (64-bit)`.
=> fix: corrected ef warning anchor link in readme

Source/Serilog.Exceptions.Grpc/Serilog.Exceptions.Grpc.csproj
and drop netstandard1.5 support from Serilog.Exceptions.Grpc
=> update to Grpc.Core.Api 2.66.0
