RehanSaeed/Serilog.Exceptions

README.md
The previous PR fixed one example, but there is one more.
=> Update first example to new RollingFile API

Source/Serilog.Exceptions/Core/ExceptionEnricher.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
Test reproducing the issue is also added.
=> Fix the exception passed to the filter

CHANGELOG.md, Tests/Serilog.Exceptions.Benchmark/Serilog.Exceptions.Benchmark.csproj
Template is taken from [keepthechangelog homepage](http://keepachangelog.com)
=> Introduce CHANGELOG.md

CHANGELOG.md, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs
=> Fix race condition in `ReflectionBasedDestructurer` cache

Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
=> Add XUnit CLI tool reference

Source/Serilog.Exceptions.EntityFrameworkCore/Destructurers/DbUpdateExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/DbUpdateExceptionDestructurerTest.cs
Sorry I missed the namespace, do want to update it?
=> Fixed: Namespace

.github/CONTRIBUTING.md, README.md
=> Document disabling reflection-based destructurer in README

Source/Serilog.Exceptions/Serilog.Exceptions.csproj
=> Allow NuGet package signing on Ubuntu and MacOS

Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs, Source/Serilog.Exceptions/Core/ExceptionEnricher.cs, Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs, Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionTypeLoadExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs, build.cake
=> Replace '!= null' with 'is object'

Serilog.Exceptions.sln, Source/Directory.Build.props, Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj, Source/Serilog.Exceptions/Serilog.Exceptions.csproj, Tests/Directory.Build.props, Tests/Serilog.Exceptions.Test/Destructurers/DbUpdateExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
=> Add Multiple nested Directory.Build.props

.github/release-drafter.yml, .github/workflows/release-drafter.yml, Serilog.Exceptions.sln
https://github.com/release-drafter/release-drafter
We'll never have to write release notes again.
=> Add release-drafter

.github/workflows/build.yml
=> Bump download-artifact from v1 to v2

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release-drafter.yml
=> Add GitHub Actions Permissions

Source/Directory.Build.props
=> Bump Microsoft.SourceLink.GitHub from 1.0.0 to 1.1.0

Directory.Build.props
=> Bump Microsoft.VisualStudio.Threading.Analyzers from 17.0.63 to 17.0.64

appveyor.yml
=> Upgrade Windows image to VS 2022

.github/workflows/build.yml
=> Use test-summary GitHub Action

.github/workflows/build.yml, Tests/Directory.Build.props
=> Remove unnecessary package

global.json
=> Bump .NET SDK from 6.0.201 to 6.0.300

Source/Directory.Build.props, global.json
=> Switch to DotNet.ReproducibleBuilds

Benchmarks/Serilog.Exceptions.Benchmark/BenchmarkExceptionDestructurer.cs, Source/Serilog.Exceptions.EntityFrameworkCore/Destructurers/DbUpdateExceptionDestructurer.cs, Source/Serilog.Exceptions.Grpc/Destructurers/RpcExceptionDestructurer.cs, Source/Serilog.Exceptions.MsSqlServer/Destructurers/SqlExceptionDestructurer.cs, Source/Serilog.Exceptions.Refit/Destructurers/ApiExceptionDestructurer.cs, Source/Serilog.Exceptions.SqlServer/Destructurers/SqlExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/AggregateExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ArgumentExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ArgumentOutOfRangeExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/IExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/OperationCanceledExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs, Source/Serilog.Exceptions/Destructurers/ReflectionTypeLoadExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/RegexMatchTimeoutExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/SocketExceptionDestructurer.cs, Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs
=> Add warning suppressions

Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj
=> Remove unused package reference

Source/Serilog.Exceptions/Serilog.Exceptions.csproj
Reverts RehanSaeed/Serilog.Exceptions#742
=> Revert "chore(deps): update dependency serilog to v3"

Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj, global.json
Reverts RehanSaeed/Serilog.Exceptions#772
=> Revert "chore(deps): update dotnet monorepo"

Directory.Build.props
so we can get the build working for CVEs first
=> temporarily disable TreatWarningsAsErrors

Directory.Build.props, Source/Serilog.Exceptions.MsSqlServer/Serilog.Exceptions.MsSqlServer.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj
* Microsoft.Data.SqlClient 5.2.2
* System.Data.SqlClient 4.8.6
=> update SqlClients to avoid CVEs

README.md
since buildstats is no longer online
=> remove history from readme

Source/Serilog.Exceptions.Refit/Destructurers/ApiExceptionDestructurer.cs, Tests/Serilog.Exceptions.Test/Destructurers/ApiExceptionDestructurerTest.cs
same as https://github.com/RehanSaeed/Serilog.Exceptions/pull/832 but with some tests added
=> Add ValidationApiException support for Refit

Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Source/Serilog.Exceptions.Grpc/Serilog.Exceptions.Grpc.csproj, Source/Serilog.Exceptions.MsSqlServer/Serilog.Exceptions.MsSqlServer.csproj, Source/Serilog.Exceptions.Refit/Serilog.Exceptions.Refit.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj, Source/Serilog.Exceptions/Serilog.Exceptions.csproj, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj, Tools/ExceptionFinderTool/ExceptionFinderTool.csproj
and Microsoft.EntityFrameworkCore V8  target and tests
=> Add explicit net8 support

Directory.Build.props, Tests/Directory.Build.props
* StyleCop.Analyzers
* Microsoft.VisualStudio.Threading.Analyzers
To many incorrect warnings
=> remove Analyzer noise

Benchmarks/Serilog.Exceptions.Benchmark/BenchmarkException.cs, Benchmarks/Serilog.Exceptions.Benchmark/Serilog.Exceptions.Benchmark.csproj, Directory.Build.props, Source/Serilog.Exceptions.EntityFrameworkCore/Serilog.Exceptions.EntityFrameworkCore.csproj, Source/Serilog.Exceptions.Grpc/Serilog.Exceptions.Grpc.csproj, Source/Serilog.Exceptions.MsSqlServer/Serilog.Exceptions.MsSqlServer.csproj, Source/Serilog.Exceptions.Refit/Serilog.Exceptions.Refit.csproj, Source/Serilog.Exceptions.SqlServer/Serilog.Exceptions.SqlServer.csproj, Source/Serilog.Exceptions/Serilog.Exceptions.csproj, Tests/Serilog.Exceptions.Test/Serilog.Exceptions.Test.csproj, Tools/ExceptionFinderTool/ExceptionFinderTool.csproj, global.json
=> Add net9 support

azure-pipelines.yml
=> install net8 and 9 in azure

Tests/Directory.Build.props, Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs
=> update test refs
